### ISSUE TITLE
Execute custom construct after cdk resources where deployed

### ISSUE THREAD

**Issue by marcotesch** [awslabs/aws-cdk#1782] opened 2019-02-18 12:57 UTC
Is there an option how one can determine on which point in time a Custom Construct will be executed?

The behavior I am observing at the moment is:

The custom resource is executed first and then all other resources are created, and the CDK Deploy runs. Would be nice if there is an option to determine at which point in time custom constructs are executed, if there is not already.

**Comment by rix0rrr** [comment] 2019-02-18 13:34
Hi @marcotesch,

Do you mean to say you have a **Custom Resource** for which you want to control at what point in the execution of `cdk deploy` your Lambda function is actually invoked (in relationship to the other resources that are defined?).

If so, you can do so by adding a *dependency* between the resources:

```ts
customResource.node.addDependency(someOtherResource);
```

If your question is about something else, I'm going to need some more details on what you're trying to accomplish please.

**Comment by marcotesch** [comment] 2019-02-18 13:40
Hi @rix0rrr,

I'm talking more or less about local execution of something after the complete `cdk deploy` cycle. And my thought was to achieve that with a CustomResource/CustomConstruct. 

It's not about execution/invocation of some Lambda Function during the `cdk deploy` in this case.

**Comment by rix0rrr** [comment] 2019-02-18 13:52
Aha. In that case, the deployment of the synthesized CDK application is the last thing that happens during a `cdk deploy` operation, and you have no opportunity to execute code *locally* after that completes.

I think your feature request is a duplicate of https://github.com/awslabs/aws-cdk/issues/922.

In any case, for now you can try to emulate this functionality using a shell script that wraps the `cdk deploy` command, or run whatever  processing you want to during deployment using a custom resource and a Lambda function.

**Closed by rix0rrr** 2019-02-18 13:52 UTC

**Comment by eladb** [comment] 2019-02-18 14:09
+1 that this is something we should support at the framework level (I would say through a nice wrapper to a custom resource logic which automatically depends on all other resources)

**Comment by marcotesch** [comment] 2019-02-18 15:32
Would be a very common feature to have something like that in the Framework.

Local Execution could be anything, for my use case typescript would be sufficient, but maybe a shell script would work as well, or any supported programming language the cdk should support.
