### ISSUE TITLE
More guidance for unit testing construction code 

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#1008] opened 2018-10-24 17:32 UTC
We have some guidance on testing construction code:
https://awslabs.github.io/aws-cdk/writing-constructs.html#testing

But users have asked for more guidance/detail/examples, including for other CDK languages.

**Comment by Doug-AWS** [comment] 2019-01-23 17:45
Is this a duplicate of #1277 ?

**Comment by rix0rrr** [comment] 2019-01-23 17:46
I think so, yes. Since the other one has more content, let's close this one.

**Closed by rix0rrr** 2019-01-23 17:46 UTC
Labels: documentation
