### ISSUE TITLE
cdk synth stack selection fails to find a stack by name

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1835] opened 2019-02-21 20:36 UTC
Repro:

```console
$ cdk synth bi-subscription-stack-us-west-2
Including dependency stacks: test-producer-us-west-2
Multiple stacks selected (test-producer-us-west-2, bi-subscription-stack-us-west-2), but output is directed to stdout. Either select one stack, or use --output to send templates to a directory.
```

**Comment by skinny85** [comment] 2019-02-21 20:51
Is this a duplicate of #1783?

**Comment by rix0rrr** [comment] 2019-02-22 10:19
It is.

**Closed by rix0rrr** 2019-02-22 10:19 UTC
Labels: bug, toolkit
