### ISSUE TITLE
Feature request - support --profile (consistency with aws cli)

### ISSUE THREAD

**Issue by eranation** [awslabs/aws-cdk#503] opened 2018-08-03 19:05 UTC
In order to switch a profile, in aws cli one can either use environment variables or use the --profile parameter. For consistency it would be nice if cdk cli would have the same support.

**Comment by rix0rrr** [comment] 2018-08-06 16:51
Duplicate of #480.

**Closed** 2018-08-08 14:42 UTC

**Comment by kennu** [comment] 2018-09-03 18:00
How do you use this option? These commands both result in the default profile being quietly used instead of the specified my-profile:

    cdk --profile my-profile deploy
    cdk deploy --profile my-profile

Meanwhile this works using the same profile:

    AWS_PROFILE=my-profile cdk deploy

Version: 0.8.2 (build 934ca5f)

**Comment by rix0rrr** [comment] 2018-11-26 08:58
Can you post a trace of running with `-v`?

**Comment by kennu** [comment] 2018-12-02 20:47
@rix0rrr I tested now with AWS CDK version 0.18.1 (build 9f7af21) and it's working correctly with `cdk --profile my-profile`, thanks.
