### ISSUE TITLE
Fn::Join no longer works with nested Fn:: methods

### ISSUE THREAD

**Issue by elexisvenator** [awslabs/aws-cdk#1076] opened 2018-11-05 00:15 UTC
Problem file: [fn.ts](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/cloudformation/fn.ts)
Problem method: FnJoin constructor
Last working version: 5bb7c93f283274263fb77445f8ffd529c37cd74b (0.13)
Broke in version: 33c32a8b88f4b2d749519ba15ab17084b3f4c822 (current, 0.14.1)

**Problem**
`FN::Join` no longer work when the `listOfValues` parameter contains another function, such as `Fn::GetAtt`.
For example, this code attempts to output the array of IP addresses for an AD Resource:

```typescript
import { cloudformation as DirectoryService } from '@aws-cdk/aws-directoryservice';
import { FnJoin } from '@aws-cdk/cdk';

const adResource = new DirectoryService.MicrosoftADResource(this, `MicrosoftADDirectoryService`, {
  vpcSettings: {
    vpcId: vpcId
    // 2 subnets = 2 ip addresses
    subnetIds: [
      subnetA,
      subnetB,
    ],
  },
  // other params here
});

// create an output, works in 0.13.x, not in 0.14.1
const ipAddressOutput = new Output(this, 'MicrosoftAdDnsIpAddresses', {
  value: new FnJoin(',', adResource.microsoftAdDnsIpAddresses.resolve() as string[])
}).makeImportValue().toString()

// workaround
const ipAddressOutput2 = new Output(this, 'MicrosoftAdDnsIpAddresses', {
  value: {
    'Fn::Join': [
      ',',
      adResource.microsoftAdDnsIpAddresses.resolve()
    ]
  },
}).makeImportValue().toString()
```

**Cause(?)**
It looks like the latest changes to `FN::Join` are designed to unpack nested joins, but I don't see how this would work if the join contained a non-join function.
There was a previous commit 59964427939e0a5b5aebef2359bc418a4bd29236 that did something similar, but was rolled back for unrelated reasons. That commit seems to be doing a lot more to make sure there were only nested joins before unpacking them.  Maybe that logic can be brought in?

Until then, I am handwriting `Fn::Join` json objects as a workaround.

**Comment by elexisvenator** [comment] 2018-11-05 00:36
For L2 instances, there is slightly different voodoo you have to do for a workaround. The cast `as unknown as string` makes me sad :(
```typescript
return new Ssm.ParameterResource(this, 'MicrosoftAdDnsIpAddressesParam', {
      name: this.domainSsmParameterPrefix + 'directory-dns',
      type: 'StringList',
      value: {
        'Fn::Join': [
          this.delimeter,
          microsoftAdDnsIpAddresses.resolve()
        ]
      } as unknown as string,
```

**Comment by rix0rrr** [comment] 2018-11-05 13:18
Thanks for reporting, having a look

**Comment by rix0rrr** [comment] 2018-11-05 13:32
I think the issue is in this line:

```ts
  value: new FnJoin(',', adResource.microsoftAdDnsIpAddresses.resolve() as string[])
```

The fact that you were able to bypass the typechecker here and make that work is actually an accident.

Related issues: https://github.com/awslabs/aws-cdk/issues/674, https://github.com/awslabs/aws-cdk/issues/744

**Comment by rix0rrr** [comment] 2018-11-05 13:37
Your current best workaround will be this:

```ts
new Fn('Fn::Join', [', ', adResource.microsoftAdDnsIpAddresses])
```

Until we sort that issue.

**Comment by rix0rrr** [comment] 2018-11-05 14:39
I'm going to close this, as your issue is a more specific case of another issue: lack of support for array tokens, and there is a workable workaround for it.

Feel free to reopen if you disagree.

**Closed by rix0rrr** 2018-11-05 14:39 UTC
