### ISSUE TITLE
documentation on how to synth, diff, and deploy from java without CLI

### ISSUE THREAD

**Issue by dsilvasc** [awslabs/aws-cdk#1133] opened 2018-11-09 11:03 UTC
It would be nice to have documentation on the readme or elsewhere on how to synth, diff, and deploy stacks with library calls instead of the cdk cli.  This is helpful when you're running from an IDE -- especially for debugging.  It's also helpful for embedding synthesis and deployment in other processes.

For example, this seems to synthesize a template from scala:

```scala
object Demo extends App {
  val cdkApp = new software.amazon.awscdk.App
  val props = StackProps.builder
    .withEnv(
      Environment.builder
        .withRegion("us-east-1")
        .build)
    .build
  val stack = MyStack(cdkApp, "stack-name", props)
  val output = cdkApp.synthesizeStack(stack.getName)
  val template = output.getTemplate.asInstanceOf[java.util.Map[String, Object]]
  println(javaMapToYAML(template)) 
}
```

It would be helpful to have a page like https://awslabs.github.io/aws-cdk/tools.html but for the library, describing `cdkApp.synthesizeStack` and friends.

**Comment by digitalsanctum** [comment] 2019-01-07 19:59
I keep coming back to this issue hoping it gets traction. This seems like it would be a huge benefit from the standpoint of using CDK for standing up and tearing down infrastructure for tests in any JVM language.

Is the current pattern to possibly use CDK to generate the template then use SDK to deploy, etc.?

**Comment by rix0rrr** [comment] 2019-01-08 08:49
Yes, that is it.

There is *something* you could do; for example, you can call `.toCloudFormation()` on your stack, which nets you part of the template, but the more advanced features like assets won't work in that scenario. At the moment, you *have* to use the CDK toolkit to interact with your CDK app.

**Comment by rix0rrr** [comment] 2019-01-08 11:35
Also a duplicate of https://github.com/awslabs/aws-cdk/issues/601, so closing this.

**Closed by rix0rrr** 2019-01-08 11:35 UTC
Labels: documentation, feature-request, java

**Comment by rix0rrr** [comment] 2019-01-08 11:36
Please upvote the linked issue.

**Comment by geek29** [comment] 2019-08-03 19:20
I have discovered that calling synth() on `App` from Java generates cloud assembly in the temp folder whereas using `cdk` commands gets that temp folder content into `./cdk.out` directory. If you are looking for template file string you can go through `/tmp/cdk.outxxxxxx` location.

**Comment by eladb** [comment] 2019-08-05 08:56
You can also specify outdir when you create the App instance.
