### ISSUE TITLE
Can we run synth programmatically?

### ISSUE THREAD

**Issue by rui-ktei** [awslabs/aws-cdk#1467] opened 2019-01-02 12:13 UTC
Hello, first of all, thank you for building this tool. I've been waiting for such tool for a long time.

I do have a TypeScript project that parses our own DSL to CloudFormation. Now with this tool, I can easily generate CloudFormation given our DSL and the generated templates will follow whatever best practices that you guys have built in - fantastic! However, instead of runniny CLI `cdk synth` everytime, is there any programmatic way to generate CloudFormation?

For example, some API like `new cdk.CfnBuilder().Build(app)` will return a list of CF stack templates that we declared in the app, this way I can easily integrate this library with our existing tool.

Thank you!

**Comment by rix0rrr** [comment] 2019-01-02 12:36
Duplicate of https://github.com/awslabs/aws-cdk/issues/601, so closing this ticket.

This request is on our radar, but at the moment the only supported method of doing this is by running the `cdk` application in a subprocess.

**Closed by rix0rrr** 2019-01-02 12:36 UTC

**Comment by rix0rrr** [comment] 2019-01-02 12:37
(Please +1 the other ticket as a signal of need to help us prioritize)
