### ISSUE TITLE
RestApi Endpoint Output Name & Export

### ISSUE THREAD

**Issue by aecollver** [awslabs/aws-cdk#1611] opened 2019-01-24 23:27 UTC
The `Endpoint` child created by RestApi doesn't seem usable because it has random characters appended to it (e.g. apiEndpoint9349E63C) and the exported name collides across multiple stack instances (I'm synthesizing the stack once in a build step and deploying multiple instances of it from CodePipeline).

Can we remove the `Endpoint` child construct so 1) I don't have to use findChild to disable exporting the output (see below) and 2) I don't have unnecessary stack outputs?

```typescript
     const restApi = new api.RestApi(this, 'api', {
      restApiName: (new cdk.AwsStackName()) as any
    });
    // Don't export the stack output because it collides when multiple
    // CloudFormation stacks are created in one account.
    restApi.findChild('Endpoint')['export'] = undefined;

    new cdk.Output(this, 'Endpoint', {
      value: restApi.urlForPath(),
      disableExport: true
    });
```

**Comment by rix0rrr** [comment] 2019-01-24 23:32
I think it makes more sense to disable exporting by default. Do you agree?

I see how the export in your case leads to conflicts. The presence of an output by itself shouldn't hurt, right?

**Comment by aecollver** [comment] 2019-01-24 23:42
> I think it makes more sense to disable exporting by default. Do you agree?

Yes

> The presence of an output by itself shouldn't hurt, right?

I imagine not in most cases, but it does contribute to the "60 outputs in a template" limit in CloudFormation (https://aws.amazon.com/cloudformation/faqs/#Limits_and_Restrictions).

That said, what is the use case for an output with random characters appended to it? In my case I wanted a stable output so it's easy to aggregate endpoints across stack instances (e.g. test, region 1, region 2).

**Comment by rix0rrr** [comment] 2019-01-24 23:57
These are for human consumption, mostly. And the characters are random, but stable.

But point taken, I'll think about it some more.

**Comment by rix0rrr** [comment] 2019-01-24 23:58
Dupe of #903

**Closed** 2019-02-05 16:37 UTC
Labels: apigateway, bug
