### ISSUE TITLE
Developer Guide: Versioning section

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#2762] opened 2019-06-05 22:53 UTC
The CDK Developer Guide should include a short section that explains versioning, talks about semver usage and expectations, etc.

**Comment by Doug-AWS** [comment] 2019-06-06 13:36
IIRC, semver means:

- If I create code in CDK v1.0, it works without change in CDK v1.x.
- If I create code in CDK v.1.0, it may need modifying to work in CDK v2.x.

We also need to explain stability.

**Comment by fulghum** [comment] 2019-06-06 16:12
@RomainMuller – probably makes sense for you to think about this content as well since it's related.

**Comment by Doug-AWS** [comment] 2019-06-06 17:12
How about: https://docs.aws.amazon.com/cdk/latest/guide/aws_construct_lib.html#aws_construct_lib_versioning

**Comment by RomainMuller** [comment] 2019-06-07 08:09
@Doug-AWS - I've rephrased it slightly in https://corp.quip-amazon.com/zHjEA5L05v1W/CDK-Versions-API-Stability

**Comment by Doug-AWS** [comment] 2019-06-07 12:41
I'll take a look and add it to the docs soon.

**Comment by RomainMuller** [comment] 2019-06-25 15:37
Duplicate of awslabs/cdk-ops#370

**Closed by RomainMuller** 2019-06-25 15:37 UTC
Labels: documentation, p0
