### ISSUE TITLE
API for aws cdk CLI commands

### ISSUE THREAD

**Issue by KarthickEmis** [awslabs/aws-cdk#2646] opened 2019-05-27 10:34 UTC
Folks, Do we have any api to synthesis aws cf templates, instead of using CLI like cdk synth , cdk deploy.

I need to create the CF template from code itself instead of using cdk cli.

**Comment by rix0rrr** [comment] 2019-05-27 14:02
Closing as duplicate of https://github.com/awslabs/aws-cdk/issues/601

**Closed by rix0rrr** 2019-05-27 14:02 UTC
