### ISSUE TITLE
Upgrading to 0.33 leads to 'Unable to determine AWS region' error

### ISSUE THREAD

**Issue by KnisterPeter** [awslabs/aws-cdk#2720] opened 2019-06-03 10:58 UTC
**Describe the bug**
Since upgrading to version 0.33 we could not run any CDK command. It fails with the following error:

```shell
(node:31487) UnhandledPromiseRejectionWarning: Error: Unable to determine AWS region from environment or AWS configuration (profile: "xxx")
    at getCLICompatibleDefaultRegion (/xxx/node_modules/aws-cdk/lib/api/util/sdk.ts:357:11)
(node:31487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Version:**
 - OS: Arch Linux
 - Programming Language: TypeScript
 - CDK Version: 0.33

**Comment by rix0rrr** [comment] 2019-06-03 12:32
Duplicate of #2697

**Closed by rix0rrr** 2019-06-03 12:32 UTC
Labels: bug
