### ISSUE TITLE
Error trying to use Lambda Code.file, Code.bucket

### ISSUE THREAD

**Issue by gaffo** [awslabs/aws-cdk#864] opened 2018-10-07 20:13 UTC
Details in https://gist.github.com/gaffo/418450aa974fe5ed5edb5352efc55248 but getting Template error: Fn::Select cannot select nonexistent value at index 1

**Comment by eladb** [comment] 2018-10-08 06:54
@gaffo I am assuming this is also caused by using an old version of the toolkit, correct?

**Comment by gaffo** [comment] 2018-10-08 06:55
Code.file worked for me, haven't had a chance to try out Code.bucket

**Comment by eladb** [comment] 2018-10-08 08:30
Okay, closing for now.

**Closed by eladb** 2018-10-08 08:30 UTC
