### ISSUE TITLE
lambda: Code.file unneccessary repeats S3 bucket parameter

### ISSUE THREAD

**Issue by coderbyheart** [awslabs/aws-cdk#678] opened 2018-09-06 15:19 UTC
For every call to `Code.file` two parameters are added to the stack, one for the object and one for the bucket.

The bucket parameter should be re-used since it will be the same for all.

**Comment by rix0rrr** [comment] 2018-09-17 10:06
Unless you're hitting CloudFormation limits because of this, I'm going to close it as "works as intended" for now.

Doing it this way affords us the flexibility to retrieve assets from different locations in the future. In any case, the assets feature will need to be redesigned shortly anyway.

**Closed by rix0rrr** 2018-09-17 10:06 UTC
